Algoritmo "tabuada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/09/2021
Var

num: inteiro
i: inteiro

Inicio

	Escreva("Digite um número")
	leia (num)
	para i de 1 ate 10 faca
	escreval (num, " x ",i," = ", num*i)
	fimpara

Fimalgoritmo